name: Unzip KernelSU

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Unzip KernelSU-main.zip
        run: |
          sudo apt update
          sudo apt install -y unzip
          unzip KernelSU-main.zip -d KernelSU
          ls KernelSU
