name: Unzip AnyKernel3

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip AnyKernel3-master.zip
        run: |
          unzip AnyKernel3-master.zip -d AnyKernel3
          echo "✅ فایل AnyKernel3-master.zip با موفقیت آنزیپ شد."

      - name: List contents
        run: ls -la AnyKernel3
