jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Update APT
        run: sudo apt update

      - name: Install unzip
        run: sudo apt install -y unzip

      - name: Download KernelSU-main.zip
        run: curl -L -o KernelSU-main.zip https://github.com/KernelSU/KernelSU/archive/refs/heads/main.zip

      - name: Unzip KernelSU-main.zip
        run: unzip KernelSU-main.zip
